/*
 * Copyright 2022 VMware, Inc.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.dbsp.sqlCompiler.compiler.visitors;

import org.apache.calcite.sql.SqlNode;
import org.apache.calcite.sql.SqlNodeList;
import org.apache.calcite.sql.parser.SqlParseException;
import org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit;
import org.dbsp.sqlCompiler.circuit.DBSPCircuit;
import org.dbsp.sqlCompiler.compiler.CompilerOptions;
import org.dbsp.sqlCompiler.compiler.sqlparser.CalciteCompiler;
import org.dbsp.sqlCompiler.compiler.frontend.statements.FrontEndStatement;
import org.dbsp.sqlCompiler.compiler.frontend.CalciteToDBSPCompiler;
import org.dbsp.sqlCompiler.compiler.frontend.TableContents;
import org.dbsp.util.IModule;
import org.dbsp.util.Logger;

import javax.annotation.Nullable;

/**
 * This class compiles SQL statements into DBSP circuits.
 * The protocol is:
 * - create compiler
 * - repeat as much as necessary:
 *   - compile a sequence of SQL statements
 *     (CREATE TABLE, CREATE VIEW)
 *   - get the resulting circuit, starting a new one
 * This protocol allows one compiler to generate multiple independent circuits.
 * The compiler can also compile INSERT statements by simulating their
 * execution and keeping track of the contents of each table.
 * The contents after insertions can be obtained using getTableContents().
 */
public class DBSPCompiler implements IModule {
    final CalciteCompiler frontend;
    final CalciteToDBSPCompiler midend;
    public final CompilerOptions options;

    public DBSPCompiler(CompilerOptions options) {
        this.options = options;
        this.frontend = new CalciteCompiler(options);
        this.midend = new CalciteToDBSPCompiler(this.frontend, true, options);
    }

    /**
     * If argument is true, the inputs to the circuit are generated from the CREATE TABLE
     * statements.  Otherwise they are generated from the LogicalTableScan
     * operations in a view plan.  Default value is 'false'.
     */
    public void setGenerateInputsFromTables(boolean generateInputsFromTables) {
        this.midend.setGenerateInputsFromTables(generateInputsFromTables);
    }

    /**
     * @param generate
     * If 'false' the next "create view" statements will not generate
     * an output for the circuit
     */
    public void generateOutputForNextView(boolean generate) {
        this.midend.generateOutputForNextView(generate);
    }

    public void compileStatement(String statement, @Nullable String comment) throws SqlParseException {
        SqlNode node = this.frontend.parse(statement);
        Logger.INSTANCE.from(this, 2)
                .append("Parsing result")
                .newline()
                .append(node.toString())
                .newline();
        FrontEndStatement fe = this.frontend.compile(statement, node, comment);
        this.midend.compile(fe);
    }

    public void compileStatement(String statement) throws SqlParseException {
        this.compileStatement(statement, null);
    }

    public void compileStatements(String program) throws SqlParseException {
        SqlNodeList nodes = this.frontend.parseStatements(program);
        for (SqlNode node: nodes) {
            FrontEndStatement fe = this.frontend.compile(node.toString(), node, null);
            this.midend.compile(fe);
        }
    }

    /**
     * Get the circuit generated by compiling the statements to far.
     * @param name  Name to use for the produced circuit.
     */
    public DBSPCircuit getFinalCircuit(String name) {
        DBSPPartialCircuit circuit = this.midend.getFinalCircuit();
        return circuit.seal(name);
    }

    /**
     * Get the contents of the tables as a result of all the INSERT statements compiled.
     */
    public TableContents getTableContents() {
        return this.midend.getTableContents();
    }
}
